// <auto-generated />
using System;
using EnergyTariffAdvisor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyTariffAdvisor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250817132611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EnergyTariffAdvisor.Models.FeedbackResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AIProfileAccurate")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CalculatorBetter")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LiveInUK")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ProjectRelevant")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedbackResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
