using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;
namespace EnergyTariffAdvisor.Models

{
    public class HouseholdSurveyTab
    {
        [Name("ID")]
        public string Id { get; set; }
        public int? A1 { get; set; }
        public int? A2a { get; set; }
        public int? A2b { get; set; }
        public int? A3 { get; set; }
        public int? A4 { get; set; }
        public int? A5 { get; set; }
        //public int? A6 { get; set; }
        //public int? A6_dn { get; set; }
        public int? A7_GAS { get; set; }
        public int? A7_ELECT { get; set; }
        public int? A7_OIL { get; set; }
        public int? A7t_LPG { get; set; }
        public int? A7_COAL { get; set; }
        public int? A7_WOODBIO { get; set; }
        public int? A8_boil_more_10 { get; set; }
        public int? A8_boil_average { get; set; }
        public int? A8_boil_condensing { get; set; }
        public int? A8_boil_new { get; set; }
        public int? A8_boil_unknown { get; set; }
        //public int? A8_boil_manual { get; set; }
        public int? A8_boil_automatic { get; set; }
        public int? A8_modern_storage { get; set; }
        public int? A8_old_storage { get; set; }
        public int? A8_roomheaters { get; set; }
        public int? A8_oil_coal_heaters { get; set; }
        public int? A8_wood_bio_stove { get; set; }
        public int? A8_openfire { get; set; }
        public int? A8_heatingsystem_other { get; set; }
        //public string? A8_OTHER { get; set; }
        public int? A9 { get; set; }
        public int? A10 { get; set; }
        //public string? A10_OTHER { get; set; }
        public int? A11 { get; set; }
        //public int? A11_TEMP { get; set; }
        public int? A12 { get; set; }
        //public int? A12_TEMP { get; set; }
        public int? A13 { get; set; }
        public int? A14 { get; set; }
        public int? A15 { get; set; }
        public int? A15_GAS { get; set; }
        public double? A15_GASBP { get; set; }
        public double? A15_GASkw { get; set; }
        public int? A15_ELECTRICITY { get; set; }
        public double? A15_ELEBP { get; set; }
        public double? A15_ELEkw { get; set; }
        public int? A15_OIL { get; set; }
        public double? A15_OILBP { get; set; }
        public double? A15_OILL { get; set; }
        public int? A15_LPG { get; set; }
        public double? A15_LGPBP { get; set; }
        public double? A15_LPGL { get; set; }
        public int? A15_COAL { get; set; }
        public double? A15_COLBP { get; set; }
        public double? A15_COLkg { get; set; }
        public int? A15_WOOD_BIOMASS { get; set; }
        public double? A15_BIOBP { get; set; }
        public double? A15_BIOkg { get; set; }
        public int? A16 { get; set; }
        public int? A17_renewa_solar { get; set; }
        public int? A17_renewa_photovolt { get; set; }
        //public int? A17_renewa_windturb { get; set; }
        public int? A17_renewa_groundheatpump { get; set; }
        public int? A17_renewa_woodbio { get; set; }
        public int? A17_renewa_hydropow { get; set; }
        public int? A17_renewa_airheatpump { get; set; }
        public int? A17_renewa_idont { get; set; }
        public int? A18_Loft { get; set; }
        public int? A18_Loft_thickness { get; set; }
        public int? A18_Cavitywall { get; set; }
        public int? A18_Solidwall { get; set; }
        public int? A18_Underfloor { get; set; }
        public int? A18_Draughtexclusion { get; set; }
        public int? A18_Doubleglazing { get; set; }
        public int? A18_Doubleglazingpercent { get; set; }
        public int? A18_Idontknow { get; set; }
        public int? A19 { get; set; }
        public int? A20 { get; set; }
        public int? A21 { get; set; }
        public int? A22_numberfridgefreezer { get; set; }
        public int? A22_agefridgefreezer { get; set; }
        public int? A22_efficiencyfridgfreez { get; set; }
        public int? t1_numberfridge { get; set; }
        public int? A22_agefridge { get; set; }
        public int? A22_efficiencyfridge { get; set; }
        public int? t1_numberfreezer { get; set; }
        public int? A22_agefreezer { get; set; }
        public int? A22_efficiencyfreezer { get; set; }
        public int? t1_numberdishwasher { get; set; }
        public int? A22_agedishwashers { get; set; }
        public int? A22_efficiencydishwasher { get; set; }
        public int? t1_dryer { get; set; }
        public int? A22_agedryer { get; set; }
        public int? A22_efficiencydryer { get; set; }
        public int? t1_washingmachine { get; set; }
        public int? A22_agewashingmachine { get; set; }
        public int? A22_efficiencywashing { get; set; }
        public int? A23 { get; set; }
        public int? A24 { get; set; }
        public int? A25 { get; set; }
        public int? A26 { get; set; }
        public int? A27 { get; set; }
        public int? A28 { get; set; }
        public int? A29 { get; set; }
        public int? A30 { get; set; }
        public int? A31 { get; set; }
        public int? A32 { get; set; }
        public int? A33 { get; set; }
        public int? A34_TVst { get; set; }
        public int? A34_TVlcd { get; set; }
        public int? A34_Tvpla { get; set; }
        public int? A34_Sat { get; set; }
        public int? A34_Cabl { get; set; }
        public int? A34_Freev { get; set; }
        public int? A34_DVD { get; set; }
        public int? A34_VCR { get; set; }
        public int? A34_PVR { get; set; }
        public int? A34_PC { get; set; }
        public int? A34_LapPC { get; set; }
        public int? A34_Inkj { get; set; }
        public int? A34_Lasr { get; set; }
        public int? A34_Scan { get; set; }
        public int? A34_Mobch { get; set; }
        public int? A34_Othch { get; set; }
        public int? A35 { get; set; }
        public int? A36 { get; set; }
        public int? A37 { get; set; }
        //public int? UR_2 { get; set; }
        //public int? UR_6 { get; set; }
    }
}