using System.Collections.Generic;
namespace EnergyTariffAdvisor.Models
{
    public static class HouseholdSurveyQuestionLabels
    {
        public static Dictionary<string, string> GetLabels()
        {
            return new Dictionary<string, string>
{
    { "ID", "Household ID" },
    { "A1", "How many people live regularly in your household?" },
    { "A2a", "What type of home do you live in? (1=Bungalow detached, 2=Bungalow semi-detached, 3=Flat/Maisonette, 4=House detached, 5=House semi-detached, 6=House mid-terrace, 7=House end-terrace, 8=Other)" },
    { "A2b", "Is the flat on the top floor? (1=Yes, 2=No)" },
    { "A3", "Do you own or rent your property? (1=Own, 2=Rent)" },
    { "A4", "How many bedrooms are there in your property? (1=1, 2=2, 3=3, 4=4, 5=5, 6=More than 5)" },
    { "A5", "How old is your property? (1=Pre 1930, 2=1930-1995, 3=post  1995)" },
    //{ "A6", "What year was your property last refurbished?" },
    //{ "A6_dn", "Refurbished [DONT KNOW]" },
    { "A7_GAS", "How do you primarily heat your home? [GAS]" },
    { "A7_ELECT", "How do you primarily heat your home? [ELECTRICITY]" },
    { "A7_OIL", "How do you primarily heat your home? [OIL]" },
    { "A7t_LPG", "How do you primarily heat your home? [LPG]" },
    { "A7_COAL", "How do you primarily heat your home? [COAL]" },
    { "A7_WOODBIO", "How do you primarily heat your home? [WOOD/BIOMASS]" },
    { "A8_boil_more_10", "What type of heating system do you have? [OLD BOILER]" },
    { "A8_boil_average", "What type of heating system do you have? [AVERAGE BOILER]" },
    { "A8_boil_condensing", "What type of heating system do you have? [CONDENSING BOILER]" },
    { "A8_boil_new", "What type of heating system do you have? [NEW BOILER]" },
    { "A8_boil_unknown", "What type of heating system do you have? [UNKNOWN AGE BOILER]" },
    //{ "A8_boil_manual", "What type of heating system do you have? [MANUAL FEED BOILER]" },
    { "A8_boil_automatic", "What type of heating system do you have? [AUTOMATIC/GRAVITY FEED BOILER]" },
    { "A8_modern_storage", "What type of heating system do you have? [MODERN STORAGE HEATERS]" },
    { "A8_old_storage", "What type of heating system do you have? [OLD STORAGE HEATERS]" },
    { "A8_roomheaters", "What type of heating system do you have? [ROOM HEATERS]" },
    { "A8_oil_coal_heaters", "What type of heating system do you have? [OIL/COAL ROOM HEATERS]" },
    { "A8_wood_bio_stove", "What type of heating system do you have? [WOOD/BIOMASS STOVE]" },
    { "A8_openfire", "What type of heating system do you have? [OPEN FIRE]" },
    { "A8_heatingsystem_other", "What type of heating system do you have? [OTHER]" },
    //{ "A8_OTHER", "Heating Type (please specify)" },
    { "A9", "What do you think is the average temperature of your living room during daytime? (1=less than 18, 2=18, 3=19, 4=20, 5=21, 6=22, 7=23, 8=24, 9=25, 10=more than 25)" },
    { "A10", "How do you heat up warm water in your household? (1=using electricity, 2=water heater or boiler running on natural gas, oil or coal, 3=district heating, 4=solar thermal system, 5=i dont know, 6=Other)" },
    //{ "A10_OTHER", "How do you heat up warm water in your household? [OTHER]" },
    { "A11", "Do you lower your heaters’ settings during the night? (1=Yes, 2=No, leave heating on, 3=No, turn heating off)" },
    //{ "A11_TEMP", "By how many degrees (at night)" },
    { "A12", "Do you lower your heaters’ settings when you are away? (1=Yes, 2=No, leave the heating on, 3=No, turn the heating off)" },
    //{ "A12_TEMP", "By how many degrees (when away)" },
    { "A13", "Do you use a green tariff option for your household electricity consumption? (1=Yes, 2=No, 3=Dont know)" },
    { "A14", "How many of the shower and water taps in your household are water-saving appliances? (1=All of them, 2=some of them, 3=none)" },
    { "A15", "Do you have your energy bills to hand, or know how much you pay on average for your energy usage? (1=Yes, 2=No)" },
    { "A15_GAS", "What kind of GAS payments do you make? (1=Not applicable, 2=Monthly, 3=Quarterly, 4=Yearly, 5=Pre-payment meter)" },
    { "A15_GASBP", "GAS Spend (£)" },
    { "A15_GASkw", "GAS Usage (kWh)" },
    { "A15_ELECTRICITY", "What kind of ELECTRICITY payments do you make? (1=Not applicable, 2=Monthly, 3=Quarterly, 4=Yearly, 5=Pre-payment meter)" },
    { "A15_ELEBP", "ELECTRICITY Spend (£)" },
    { "A15_ELEkw", "ELECTRICITY Usage (kWh)" },
    { "A15_OIL", "What kind of OIL payments do you make? (1=Not applicable, 2=Monthly, 3=On delivery, 4=Yearly)" },
    { "A15_OILBP", "OIL Spend (£)" },
    { "A15_OILL", "OIL Usage (kWh)" },
    { "A15_LPG", "What kind of LPG payments do you make? (1=Not applicable, 2=Monthly, 3=On delivery, 4=Yearly)" },
    { "A15_LGPBP", "LPG Spend (£)" },
    { "A15_LPGL", "LPG Usage (kWh)" },
    { "A15_COAL", "What kind of COAL payments do you make? (1=Not applicable, 2=Monthly, 3=On delivery, 4=Yearly)" },
    { "A15_COLBP", "COAL Spend (£)" },
    { "A15_COLkg", "COAL Usage (kWh)" },
    { "A15_WOOD_BIOMASS", "What kind of WOOD/BIOMASS payments do you make? (1=Not applicable, 2=Monthly, 3=On delivery, 4=Yearly)" },
    { "A15_BIOBP", "WOOD/BIOMASS Spend (£)" },
    { "A15_BIOkg", "WOOD/BIOMASS Usage (kWh)" },
    { "A16", "Do you have a real time display?" },
    { "A17_renewa_solar", "Solar hot water" },
    { "A17_renewa_photovolt", "Photovoltaic solar panels" },
    //{ "A17_renewa_windturb", "Wind turbine" },
    { "A17_renewa_groundheatpump", "Ground source heat pump" },
    { "A17_renewa_woodbio", "Wood/Biomass heating" },
    { "A17_renewa_hydropow", "Hydro power" },
    { "A17_renewa_airheatpump", "Air source heat pump" },
    { "A17_renewa_idont", "I don’t use any of these (renewables)" },
    { "A18_Loft", "Do you have loft insulation?" },
    { "A18_Loft_thickness", "How much loft insulation? (approximately) (1=12mm, 2=25mm, 3=50mm, 4=75mm, 5=100mm, 6=150mm, 7=200mm, 8=250mm, 9=300mm)" },
    { "A18_Cavitywall", "Do you have cavity wall insulation?" },
    { "A18_Solidwall", "Do you have solid wall insulation?" },
    { "A18_Underfloor", "Do you have underfloor insulation?" },
    { "A18_Draughtexclusion", "Do you have draught exclusion insulation?" },
    { "A18_Doubleglazing", "Do you have double glazing?" },
    { "A18_Doubleglazingpercent", "How many of your windows are double glazed? (1=100%, 2=75%, 3=50%, 4=25%)" },
    { "A18_Idontknow", "Insulation [I DON'T KNOW]" },
    { "A19", "Approximately how many lightbulbs does your house have?" },
    { "A20", "How many of these lights have you swapped for low energy lightbulbs?" },
    { "A21", "How often do you turn lights off when nobody is using them? (1=Never, 7=Always)" },
    { "A22_numberfridgefreezer", "Fridge-Freezer [NUMBER]" },
    { "A22_agefridgefreezer", "Fridge-Freezer [AGE] (1=1-12 years, 2=over 12 years, 3=i don't know)" },
    { "A22_efficiencyfridgfreez", "Fridge-Freezer [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "t1_numberfridge", "Fridge [NUMBER]" },
    { "A22_agefridge", "Fridge [AGE] (1=1-12 years, 2=over 12 years, 3=i don't know)" },
    { "A22_efficiencyfridge", "Fridge [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "t1_numberfreezer", "Freezer [NUMBER]" },
    { "A22_agefreezer", "Freezer [AGE] (1=1-12 years, 2=over 12 years, 3=i don't know)" },
    { "A22_efficiencyfreezer", "Freezer [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "t1_numberdishwasher", "Dish Washer [NUMBER]" },
    { "A22_agedishwashers", "Dish Washer [AGE] (1=1-2 years, 2=3-5 years, 3=over 5 years, 4=i don't know)" },
    { "A22_efficiencydishwasher", "Dish Washer [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "t1_dryer", "Dryer [NUMBER]" },
    { "A22_agedryer", "Dryer [AGE] (1=1-12 years, 2=over 12 years, 3=i don't know)" },
    { "A22_efficiencydryer", "Dryer [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "t1_washingmachine", "Washing Machine [NUMBER]" },
    { "A22_agewashingmachine", "Washing Machine [AGE] (1=1-12 years, 2=over 12 years, 3=i don't know)" },
    { "A22_efficiencywashing", "Washing Machine [EFFICIENCY] (1=A++, 2=A+, 3=A, 4=B, 5=C, 6=D, 7=E, 8=F, 9=G)" },
    { "A23", "What type of hob do you have? (1=Gas, 2=Standard Electric, 3=Induction Electric, 4=I don't have one)" },
    { "A24", "What kind of oven do you have? (1=Gas, 2=Electric, 3=I dont have one)" },
    { "A25", "Do you own a microwave? (1=Yes, 2=No)" },
    { "A26", "How many loads of washing (laundry) do you do a week?" },
    { "A27", "What is the average temperature setting that you use for washing clothes? (1=30 degrees, 2=40 degrees, 3=60 degrees, 4=90 degrees)" },
    { "A28", "When the washing machine is used, how often is it full? (1=Never, 7=Always)" },
    { "A29", "How often do you hang your laundry outside to dry? (1=Often, 2=Sometimes, 3=Never)" },
    { "A30", "How often do you hang your laundry inside to dry? (1=Often, 2=Sometimes, 3=Never)" },
    { "A31", "How many times a week do you take a bath?" },
    { "A32", "How many times a week do you take a shower?" },
    { "A33", "How long do you take to have a shower, on average?" },
    { "A34_TVst", "[NUMBER] Standard (CRT)" },
    { "A34_TVlcd", "[NUMBER] LCD / Flatscreen" },
    { "A34_Tvpla", "[NUMBER] Plasma" },
    { "A34_Sat", "[NUMBER] Satellite box" },
    { "A34_Cabl", "[NUMBER] Cable box" },
    { "A34_Freev", "[NUMBER] Freeview" },
    { "A34_DVD", "[NUMBER] DVD player / recorder" },
    { "A34_VCR", "[NUMBER] VCR (video)" },
    { "A34_PVR", "[NUMBER] Personal Video Recorder (with HDD)" },
    { "A34_PC", "[NUMBER] Desktop computer" },
    { "A34_LapPC", "[NUMBER] Laptop computer" },
    { "A34_Inkj", "[NUMBER] Inkjet printer" },
    { "A34_Lasr", "[NUMBER] Laser Printer" },
    { "A34_Scan", "[NUMBER] Scanner" },
    { "A34_Mobch", "[NUMBER] Mobile phone charger" },
    { "A34_Othch", "[NUMBER] Other appliance charger" },
    { "A35", "How often do you leave your entertainment equipment on standby? (1=All of the time, 2=Most of the time, 3=Some fo the time, 4=Never)" },
    { "A36", "How often do you leave computer equipment on when you are not actively using it? (1=All of the time, 2=Most of the time, 3=Some fo the time, 4=Never)" },
    { "A37", "How many hours of television (on average) do you watch per day?" }
    //{ "UR_2", "URBAN-RURAL 2-FOLD CLASSIFICATION" },
    //{ "UR_6", "URBAN-RURAL 6-FOLD CLASSIFICATION" }
};

        }
    }
}