using System.Collections.Generic;
namespace EnergyTariffAdvisor.Models
{
    public static class HouseholdSurveyQuestionLabels
    {
        public static Dictionary<string, string> GetLabels()
        {
            return new Dictionary<string, string>
            {
                { "ID", "Household ID" },
                { "A1", "How many people live regularly in your household?" },
                { "A2a", "What type of home do you live in?" },
                { "A2b", "Is the flat on the top floor?" },
                { "A3", "Do you own or rent your property?" },
                { "A4", "How many bedrooms are there in your property?" },
                { "A5", "How old is your property?" },
                { "A6", "What year was your property last refurbished?" },
                { "A6_dn", "Refurbished [DONT KNOW]" },
                { "A7_GAS", "How do you primarily heat your home? [GAS]" },
                { "A7_ELECT", "How do you primarily heat your home? [ELECTRICITY]" },
                { "A7_OIL", "How do you primarily heat your home? [OIL]" },
                { "A7t_LPG", "How do you primarily heat your home? [LPG]" },
                { "A7_COAL", "How do you primarily heat your home? [COAL]" },
                { "A7_WOODBIO", "How do you primarily heat your home? [WOOD/BIOMASS]" },
                { "A8_boil_more_10", "What type of heating system do you have? [OLD BOILER]" },
                { "A8_boil_average", "What type of heating system do you have? [AVERAGE BOILER]" },
                { "A8_boil_condensing", "What type of heating system do you have? [CONDENSING BOILER]" },
                { "A8_boil_new", "What type of heating system do you have? [NEW BOILER]" },
                { "A8_boil_unknown", "What type of heating system do you have? [UNKNOWN AGE BOILER]" },
                { "A8_boil_manual", "What type of heating system do you have? [MANUAL FEED BOILER]" },
                { "A8_boil_automatic", "What type of heating system do you have? [AUTOMATIC/GRAVITY FEED BOILER]" },
                { "A8_modern_storage", "What type of heating system do you have? [MODERN STORAGE HEATERS]" },
                { "A8_old_storage", "What type of heating system do you have? [OLD STORAGE HEATERS]" },
                { "A8_roomheaters", "What type of heating system do you have? [ROOM HEATERS]" },
                { "A8_oil_coal_heaters", "What type of heating system do you have? [OIL/COAL ROOM HEATERS]" },
                { "A8_wood_bio_stove", "What type of heating system do you have? [WOOD/BIOMASS STOVE]" },
                { "A8_openfire", "What type of heating system do you have? [OPEN FIRE]" },
                { "A8_heatingsystem_other", "What type of heating system do you have? [OTHER]" },
                { "A8_OTHER", "Heating Type (please specify)" },
                { "A9", "What do you think is the average temperature of your living room during daytime?" },
                { "A10", "How do you heat up warm water in your household?" },
                { "A10_OTHER", "How do you heat up warm water in your household? [OTHER]" },
                { "A11", "Do you lower your heaters’ settings during the night?" },
                { "A11_TEMP", "By how many degrees (at night)" },
                { "A12", "Do you lower your heaters’ settings when you are away?" },
                { "A12_TEMP", "By how many degrees (when away)" },
                { "A13", "Do you use a green tariff option for your household electricity consumption?" },
                { "A14", "How many of the shower and water taps in your household are water-saving appliances?" },
                { "A15", "Do you have your energy bills to hand, or know how much you pay on average for your energy usage?" },
                { "A15_GAS", "What kind of GAS payments do you make?" },
                { "A15_GASBP", "GAS Spend (£)" },
                { "A15_GASkw", "GAS Usage (kWh)" },
                { "A15_ELECTRICITY", "What kind of ELECTRICITY payments do you make?" },
                { "A15_ELEBP", "ELECTRICITY Spend (£)" },
                { "A15_ELEkw", "ELECTRICITY Usage (kWh)" },
                { "A15_OIL", "What kind of OIL payments do you make?" },
                { "A15_OILBP", "OIL Spend (£)" },
                { "A15_OILL", "OIL Usage (kWh)" },
                { "A15_LPG", "What kind of LPG payments do you make?" },
                { "A15_LGPBP", "LPG Spend (£)" },
                { "A15_LPGL", "LPG Usage (kWh)" },
                { "A15_COAL", "What kind of COAL payments do you make?" },
                { "A15_COLBP", "COAL Spend (£)" },
                { "A15_COLkg", "COAL Usage (kWh)" },
                { "A15_WOOD_BIOMASS", "What kind of WOOD/BIOMASS payments do you make?" },
                { "A15_BIOBP", "WOOD/BIOMASS Spend (£)" },
                { "A15_BIOkg", "WOOD/BIOMASS Usage (kWh)" },
                { "A16", "Do you have a real time display?" },
                { "A17_renewa_solar", "Solar hot water" },
                { "A17_renewa_photovolt", "Photovoltaic solar panels" },
                { "A17_renewa_windturb", "Wind turbine" },
                { "A17_renewa_groundheatpump", "Ground source heat pump" },
                { "A17_renewa_woodbio", "Wood/Biomass heating" },
                { "A17_renewa_hydropow", "Hydro power" },
                { "A17_renewa_airheatpump", "Air source heat pump" },
                { "A17_renewa_idont", "I don’t use any of these (renewables)" },
                { "A18_Loft", "Do you have loft insulation?" },
                { "A18_Loft_thickness", "How much loft insulation? (approximately)" },
                { "A18_Cavitywall", "Do you have cavity wall insulation?" },
                { "A18_Solidwall", "Do you have solid wall insulation?" },
                { "A18_Underfloor", "Do you have underfloor insulation?" },
                { "A18_Draughtexclusion", "Do you have draught exclusion insulation?" },
                { "A18_Doubleglazing", "Do you have double glazing?" },
                { "A18_Doubleglazingpercent", "How many of your windows are double glazed?" },
                { "A18_Idontknow", "Insulation [I DON'T KNOW]" },
                { "A19", "Approximately how many lightbulbs does your house have?" },
                { "A20", "How many of these lights have you swapped for low energy lightbulbs?" },
                { "A21", "How often do you turn lights off when nobody is using them?" },
                { "A22_numberfridgefreezer", "Fridge-Freezer [NUMBER]" },
                { "A22_agefridgefreezer", "Fridge-Freezer [AGE]" },
                { "A22_efficiencyfridgfreez", "Fridge-Freezer [EFFICIENCY]" },
                { "t1_numberfridge", "Fridge [NUMBER]" },
                { "A22_agefridge", "Fridge [AGE]" },
                { "A22_efficiencyfridge", "Fridge [EFFICIENCY]" },
                { "t1_numberfreezer", "Freezer [NUMBER]" },
                { "A22_agefreezer", "Freezer [AGE]" },
                { "A22_efficiencyfreezer", "Freezer [EFFICIENCY]" },
                { "t1_numberdishwasher", "Dish Washer [NUMBER]" },
                { "A22_agedishwashers", "Dish Washer [AGE]" },
                { "A22_efficiencydishwasher", "Dish Washer [EFFICIENCY]" },
                { "t1_dryer", "Dryer [NUMBER]" },
                { "A22_agedryer", "Dryer [AGE]" },
                { "A22_efficiencydryer", "Dryer [EFFICIENCY]" },
                { "t1_washingmachine", "Washing Machine [NUMBER]" },
                { "A22_agewashingmachine", "Washing Machine [AGE]" },
                { "A22_efficiencywashing", "Washing Machine [EFFICIENCY]" },
                { "A23", "What type of hob do you have?" },
                { "A24", "What kind of oven do you have?" },
                { "A25", "Do you own a microwave?" },
                { "A26", "How many loads of washing (laundry) do you do a week?" },
                { "A27", "What is the average temperature setting that you use for washing clothes?" },
                { "A28", "When the washing machine is used, how often is it full?" },
                { "A29", "How often do you hang your laundry outside to dry?" },
                { "A30", "How often do you hang your laundry inside to dry?" },
                { "A31", "How many times a week do you take a bath?" },
                { "A32", "How many times a week do you take a shower?" },
                { "A33", "How long do you take to have a shower, on average?" },
                { "A34_TVst", "[NUMBER] Standard (CRT)" },
                { "A34_TVlcd", "[NUMBER] LCD / Flatscreen" },
                { "A34_Tvpla", "[NUMBER] Plasma" },
                { "A34_Sat", "[NUMBER] Satellite box" },
                { "A34_Cabl", "[NUMBER] Cable box" },
                { "A34_Freev", "[NUMBER] Freeview" },
                { "A34_DVD", "[NUMBER] DVD player / recorder" },
                { "A34_VCR", "[NUMBER] VCR (video)" },
                { "A34_PVR", "[NUMBER] Personal Video Recorder (with HDD)" },
                { "A34_PC", "[NUMBER] Desktop computer" },
                { "A34_LapPC", "[NUMBER] Laptop computer" },
                { "A34_Inkj", "[NUMBER] Inkjet printer" },
                { "A34_Lasr", "[NUMBER] Laser Printer" },
                { "A34_Scan", "[NUMBER] Scanner" },
                { "A34_Mobch", "[NUMBER] Mobile phone charger" },
                { "A34_Othch", "[NUMBER] Other appliance charger" },
                { "A35", "How often do you leave your entertainment equipment on standby?" },
                { "A36", "How often do you leave computer equipment on when you are not actively using it?" },
                { "A37", "How many hours of television (on average) do you watch per day?" },
                { "UR_2", "URBAN-RURAL 2-FOLD CLASSIFICATION" },
                { "UR_6", "URBAN-RURAL 6-FOLD CLASSIFICATION" }
            };
        }
    }
}